
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.cargo]
target = "armv5te-nintendo-ds.json"
[language-server.rust-analyzer.config.check]
allTargets = false
